### ISSUE TITLE
I/O Testing - Chris, Stephen

### ISSUE THREAD

**Issue by redragonx** [redragonx/FAA-CS-4250#3]
Tests to be generated:
- [x] ADS input:  COMPLETE
- [X] keyboard input: COMPLETE
- [x] audio alerts:  COMPLETE

**Comment by auroraaxela** [comment]
Testing complete for input data from ADS-B. Ready to send lists to plane_controller.
Singular data verification for completeness is performed within the parse function in ADS_io

**Comment by auroraaxela** [comment]
Testing complete for audio alerts from all sources. Will progress with implementation by assigning all audio messages to their respective audio files.

**Comment by auroraaxela** [comment]
Testing complete for keypad input. Further work on implementation of keypad input is in progress.
